version: "3"
services:
  irankiai:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./irankiai
        target: /usr/src/app
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: username
      POSTGRES_DB: irankiai

volumes:
  conference_app:
