# Generated by Django 4.2.1 on 2023-08-10 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrankioAtsiliepimas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atsiliepimas', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Atsiliepimas',
                'verbose_name_plural': 'Atsiliepimai',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='IrankioVienetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akumuliatoriaus_talpa', models.IntegerField(blank=True, null=True)),
                ('QR_kodas', models.CharField(max_length=255)),
                ('ar_isnuomotas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Irankis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('power', models.IntegerField(blank=True, null=True, verbose_name='power of electric tool')),
                ('delivery', models.BooleanField(verbose_name='delivery')),
                ('nuotrauka', models.ImageField(blank=True, null=True, upload_to='irankis')),
            ],
            options={
                'verbose_name': 'Įrankis',
                'verbose_name_plural': 'Įrankiai',
            },
        ),
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='NuomosFaktas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastabos', models.TextField()),
                ('irankio_vienetas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='irankis.irankiovienetas')),
            ],
            options={
                'verbose_name': 'Nuomos faktas',
                'verbose_name_plural': 'Nuomos faktai',
            },
        ),
    ]
