# Generated by Django 4.2.1 on 2023-05-17 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Irankis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
                ('aprasymas', models.TextField(blank=True, null=True)),
                ('galia', models.IntegerField(blank=True, null=True)),
                ('pristatymas', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NuomosFaktas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastabos', models.TextField()),
                ('irankis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='irankis.irankis')),
            ],
        ),
    ]
