# Generated by Django 4.2.1 on 2023-06-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('naudotojo_profilis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrankioVienetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akumuliatoriaus_talpa', models.IntegerField(blank=True, null=True)),
                ('vietove', models.CharField(max_length=255)),
                ('QR_kodas', models.CharField(max_length=255)),
                ('ar_isnuomotas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NuomosFaktas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastabos', models.TextField()),
                ('irankio_vienetas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='irankis.irankiovienetas')),
                ('nuomininkas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuomininko_nuomos_faktai', to='naudotojo_profilis.naudotojoprofilis')),
                ('nuomotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuomotojo_nuomos_faktai', to='naudotojo_profilis.naudotojoprofilis')),
            ],
            options={
                'verbose_name': 'Nuomos faktas',
                'verbose_name_plural': 'Nuomos faktai',
            },
        ),
        migrations.CreateModel(
            name='Irankis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
                ('aprasymas', models.TextField(blank=True, null=True)),
                ('galia', models.IntegerField(blank=True, null=True)),
                ('pristatymas', models.BooleanField()),
                ('nuotrauka', models.ImageField(blank=True, null=True, upload_to='irankis')),
                ('kategorijos', models.ManyToManyField(to='irankis.kategorija')),
                ('naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naudotojo_profilis.naudotojoprofilis')),
            ],
            options={
                'verbose_name': 'Įrankis',
                'verbose_name_plural': 'Įrankiai',
            },
        ),
        migrations.AddField(
            model_name='irankiovienetas',
            name='irankis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irankis.irankis'),
        ),
    ]
