# Generated by Django 4.2.1 on 2023-06-14 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('irankis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irankiovienetas',
            name='vietove',
        ),
        migrations.AlterField(
            model_name='irankis',
            name='aprasymas',
            field=models.TextField(blank=True, null=True, verbose_name='aprašymas'),
        ),
        migrations.AlterField(
            model_name='irankis',
            name='galia',
            field=models.IntegerField(blank=True, null=True, verbose_name='elektrinio įrankio galia'),
        ),
        migrations.CreateModel(
            name='IrankioAtsiliepimas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atsiliepimas', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('irankis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irankis.irankis')),
                ('naudotojas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
