# Generated by Django 4.2.1 on 2023-05-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irankis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='irankis',
            options={'verbose_name': 'Įrankis', 'verbose_name_plural': 'Įrankiai'},
        ),
        migrations.AlterModelOptions(
            name='nuomosfaktas',
            options={'verbose_name': 'Nuomos faktas', 'verbose_name_plural': 'Nuomos faktai'},
        ),
        migrations.AddField(
            model_name='irankis',
            name='kategorijos',
            field=models.ManyToManyField(to='irankis.kategorija'),
        ),
    ]
