# Generated by Django 4.2.1 on 2023-07-24 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('irankis', '0003_alter_irankioatsiliepimas_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irankis',
            name='aprasymas',
        ),
        migrations.RemoveField(
            model_name='irankis',
            name='galia',
        ),
        migrations.RemoveField(
            model_name='irankis',
            name='pavadinimas',
        ),
        migrations.RemoveField(
            model_name='irankis',
            name='pristatymas',
        ),
        migrations.AddField(
            model_name='irankis',
            name='delivery',
            field=models.BooleanField(default=True, verbose_name='delivery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irankis',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='irankis',
            name='name',
            field=models.CharField(default=' ', max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irankis',
            name='power',
            field=models.IntegerField(blank=True, null=True, verbose_name='power of electric tool'),
        ),
        migrations.AlterField(
            model_name='irankioatsiliepimas',
            name='irankis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='irankis.irankis'),
        ),
        migrations.AlterField(
            model_name='irankioatsiliepimas',
            name='naudotojas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
