# Generated by Django 4.2.1 on 2023-07-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naudotojo_profilis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naudotojoprofilis',
            name='ivertinimas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
